server:
  port: 3003
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:3004/eureka/, http://localhost:3001/eureka/
spring:
  application:
    name: server3003
