server:
  port: 3003
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: server2
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/, http://localhost:3004/eureka/
