server:
  port: 3004
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: server3
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/, http://localhost:3003/eureka/

