server:
  port: 6001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3004/eureka/,http://localhost:3001/eureka,http://localhost:3003/eureka
    instance:
      instance-id: power-2
      prefer-ip-address: true
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30
spring:
  application:
    name: server-power