server:
    port: 3001
eureka:
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
    instance:
        hostname: server1
    client:
        serviceUrl:
            defaultZone: http://localhost:3003/eureka/, http://localhost:3004/eureka/